<?php include 'header.php'; ?>
          <div class="moto-widget moto-widget-block moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-large moto-spacing-left-auto" data-widget="block" data-spacing="lala" style="" data-draggable-disabled="">
              <div class="container-fluid">
                  <div class="row">
                      <div class="moto-cell col-sm-12" data-container="container">
                          <div class="moto-widget moto-widget-row row-fixed moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" data-grid-type="sm" data-widget="row" data-spacing="aaaa" style="" data-draggable-disabled="">
                              <div class="container-fluid">
                                  <div class="row" data-container="container">
                                      <div class="moto-widget moto-widget-row__column moto-cell col-sm-12 moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" style="" data-widget="row.column" data-container="container" data-spacing="aaaa">
                                          <div class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-auto moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" data-widget="text" data-preset="default" data-spacing="aaaa" data-animation="" data-draggable-disabled="">
                                              <div class="moto-widget-text-content moto-widget-text-editable">
                                                <p class="moto-text_system_7" style="text-align: center;">Genel bilgi</p>
                                                <p class="moto-text_normal" style="text-align: center;">Gizlilik Politikası sayfamıza hoşgeldiniz! Web sitesi hizmetlerimizi kullandığınızda, bize bilgilerinize güvenin. Bu Gizlilik Politikası, hangi verileri topladığımızı, neden topladığımızı ve bununla ne yaptığımızı anlamanıza yardımcı olmayı amaçlamaktadır. Bizimle bilgi paylaştığınızda, hizmetlerimizi sizin için daha da iyi hale getirebiliriz. Örneğin, size daha alakalı arama sonuçları ve reklamlar gösterebilir, kullanıcılarla iletişim kurmanıza veya başkalarıyla daha hızlı ve kolay paylaşımda bulunmanıza yardımcı olabiliriz. Hizmetlerimizi kullandığınız için, bilgileri nasıl kullandığımızı ve gizliliğinizi nasıl koruyabileceğinizi anlamanızı istiyoruz. Bu önemli; Umarım dikkatlice okumak için zaman alırsınız. Unutmayın, bilgilerinizi yönetmek ve gizliliğinizi ve güvenliğinizi korumak için kontrolleri bulabilirsiniz. Olabildiğince basit tutmaya çalıştık.</p>
                                                <p class="moto-text_normal" style="text-align: center;"><br></p>
                                                <p class="moto-text_system_7" style="text-align: center;">Veri İşleme ve Veriye Veri İşleme ve Düzeltme Hakkı</p>
                                                <p class="moto-text_normal" style="text-align: center;">Müşterilerimiz, kendileriyle ilgili kişisel verilere erişme, düzeltme ve silme ve yazılı bir talebi yerine getirme, bu verilerin işlenmesine itiraz etme hakkına sahiptir. Şirket, kişisel verilerin güvenliğini ve mahremiyetini korumak ve yetkisiz üçüncü kişiler tarafından değiştirilmesini, bozulmasını, yok edilmesini veya erişilmesini önlemek için gerekli önlemleri almak için her türlü çabayı göstermektedir. Bununla birlikte, Şirket, İnternet'in kullanımı ile ilgili her bir riski kontrol etmemektedir ve bu nedenle Site kullanıcılarını, İnternet'in işleyişinde ve kullanılmasında yer alan potansiyel riskler konusunda uyarmaktadır. Site, diğer web sitelerine veya diğer internet kaynaklarına bağlantılar içerebilir. Şirket bu web sitelerini ve harici kaynakları kontrol edemediğinden,</p>
                                                <p class="moto-text_normal" style="text-align: center;"><br></p>
                                                <p class="moto-text_system_7" style="text-align: center;">Kişisel Verilerin Yönetimi</p>
                                                <p class="moto-text_normal" style="text-align: center;">Kişisel verilerinizi, hizmetlerimizin çoğu için çevrimiçi olarak görüntüleyebilir veya düzenleyebilirsiniz. Verilerinizin toplanması ve kullanımı hakkında da seçim yapabilirsiniz. Kişisel verilerinize nasıl erişebileceğiniz veya bunları kontrol edebileceğiniz, kullandığınız hizmetlere bağlı olacaktır. Web sitemizden e-posta, SMS, fiziki posta ve telefon yoluyla promosyon iletişimi almak isteyip istemediğinizi seçebilirsiniz. Bizden promosyon e-postası veya SMS mesajı alırsanız ve çıkmak istemiyorsanız, bu mesajdaki talimatları izleyerek bunu yapabilirsiniz. Ayrıca, iletişim bilgilerini güncellemenize, iletişim tercihlerini yönetmenize, e-posta aboneliklerini devre dışı bırakmanıza ve şirket yetkilileriyle iletişim kurmanıza olanak tanıyan Şirket Tanıtım İletişimi Yöneticisi'ni ziyaret edip imzalayarak promosyon e-postasının, telefon görüşmelerinin ve posta postasının alınmasıyla ilgili seçenekler de yapabilirsiniz. iletişim bilgilerinizi ortaklarımızla paylaşın.</p>
                                                <p class="moto-text_normal" style="text-align: center;"><br></p>
                                                <p class="moto-text_system_7" style="text-align: center;">Topladığımız Bilgiler</p>
                                                <p class="moto-text_normal" style="text-align: center;">Mağazamız etkili bir şekilde çalışmak için veri toplar ve hizmetlerimizle size en iyi deneyimleri sunar. Kişisel bir hesap oluşturduğunuzda, bu verilerin bir kısmını doğrudan sağlarsınız. Servislerimizle nasıl etkileşimde bulunduğunuzu, örneğin çerezler gibi teknolojiler kullanarak ve cihazınızda çalışan yazılımlardan hata raporları veya kullanım verileri alarak nasıl kaydedildiğimizi kaydediyoruz. Ayrıca üçüncü taraflardan (diğer şirketler dahil) veri elde ederiz. Örneğin, topladığımız verileri diğer şirketlerden demografik veriler satın alarak tamamlıyoruz. Belirli hizmetleri kendi konumunuza göre özelleştirmek için, IP adresinize dayalı bir yer belirlememize yardımcı olmak için diğer şirketlerden de hizmetler kullanıyoruz. Topladığımız veriler, kullandığınız hizmetlere ve özelliklere bağlıdır.</p>
                                                <p class="moto-text_normal" style="text-align: center;"><br></p>
                                                <p class="moto-text_system_7" style="text-align: center;">Bilgilerinizi Nasıl Kullanıyoruz</p>
                                                <p class="moto-text_normal" style="text-align: center;">Web sitemiz topladığımız verileri üç temel amaç için kullanır: işimizi yürütmek ve sunduğumuz hizmetleri sağlamak (promosyon ve kişiselleştirme dahil), promosyon iletişimi de dahil olmak üzere iletişimi sağlamak ve reklam göstermek. Bu amaçları gerçekleştirirken, topladığımız verileri size daha sorunsuz, tutarlı ve kişiselleştirilmiş bir deneyim sunmak için kullandığınız çeşitli web sitesi hizmetleriyle birleştiriyoruz. Ancak, gizliliği artırmak için, belirli veri kombinasyonlarını önlemek üzere tasarlanmış teknolojik ve prosedürsel önlemler oluşturduk. Örneğin, kimliğinizi doğrudan doğruya belirleyeceğiniz (adınız, e-posta adresiniz veya telefon numaranız gibi) hesap bilgilerinizden bağımsız olarak kimliğinizin dışında (sizde oturum açmamış olduğunuz) sizden topladığımız verileri saklarız.</p>
                                                <p class="moto-text_normal" style="text-align: center;"><br></p>
                                                <p class="moto-text_system_7" style="text-align: center;">Bilgilerinizi Paylaşma</p>
                                                <p class="moto-text_normal" style="text-align: center;">Kişisel verilerinizi rızanızla paylaşırız ya da herhangi bir işlemi tamamlamak veya talep ettiğiniz veya yetki verdiğiniz herhangi bir hizmeti sunmak için gereklidir. Örneğin, bunu yaptığınızda, içeriğinizi üçüncü taraflarla paylaşıyoruz. Bir satın alma işlemi yapmak için ödeme verileri sağladığınızda, ödeme verilerini ödeme işlemlerini gerçekleştiren veya diğer finansal hizmetleri sağlayan bankalar ve diğer kuruluşlarla ve sahteciliği önleme ve kredi riski azaltımıyla paylaşacağız. Ayrıca, kişisel verileri kontrollü iştiraklerimiz ve iştiraklerimiz arasında paylaşıyoruz. Ayrıca kişisel verileri, bu beyannamede açıklanan amaçlar için bizim adımıza çalışan satıcılarla veya aracılarla paylaşırız. Örneğin, biz şirketler Müşteri hizmet desteği sağlamak için işe alınmış veya sistemlerimizi ve hizmetlerimizi koruma ve güvenceye almada yardımcı olmak, bu işlevleri sağlamak için kişisel verilere erişebilir. Bu gibi durumlarda, bu şirketler veri gizliliği ve güvenlik şartlarımıza uymak zorundadır ve bizden aldıkları kişisel bilgileri başka herhangi bir amaçla kullanamazlar. Kişisel verileri, birleşme veya varlıkların satışı gibi kurumsal bir işlemin parçası olarak da açıklayabiliriz.</p>
                                                <p class="moto-text_normal" style="text-align: center;"><br></p>
                                                <p class="moto-text_normal" style="text-align: center;"><br></p>
                                                <p class="moto-text_normal" style="text-align: center;"><a href="mailto:privacy@sacekimi.com" data-action="mail" class="moto-link">privacy@sacekimi.com</a></p>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
        </section>
    </div>
    <?php include 'footer.php'; ?>
